github: [PauloHSOliveira]  
patreon: cosmstack                 
open_collective: null
ko_fi: null
tidelift: null
community_bridge: null
liberapay: null
issuehunt: null
lfx_crowdfunding: null
polar: null
buy_me_a_coffee: null
thanks_dev: null
custom: null
